services:
    action.patient.list:
        parent: core.action.abstract
        class: AppBundle\Action\ListAction
        arguments:
            - AppBundle\Entity\Patient
        calls: [['setOptions', [{filters: ['status', 'groups', 'query']}]]]
    action.group.list:
        parent: core.action.abstract
        class: Requestum\ApiBundle\Action\ListAction
        arguments:
            - AppBundle\Entity\Group