services:
    action.patient.list:
        parent: core.action.abstract
        class: AppBundle\Action\ListAction
        arguments:
            - AppBundle\Entity\Patient
            - "@router"
        calls: [['setOptions', [{filters: ['status', 'groups', 'query', 'order-by']}]]]
    action.group.list:
        parent: core.action.abstract
        class: Requestum\ApiBundle\Action\ListAction
        arguments:
            - AppBundle\Entity\Group
        calls: [['setOptions', [{filters: ['active']}]]]