<?php
/**
 * Created by PhpStorm.
 * User: basil
 * Date: 12.12.17
 * Time: 22:58
 */

namespace AppBundle\Action;


use Pagerfanta\Pagerfanta;
use Symfony\Component\HttpFoundation\Response;

class ListAction extends \Requestum\ApiBundle\Action\ListAction
{
    /**
     * @param Pagerfanta $data
     * @param int $status
     * @param array $serializationContext
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     */
    protected function handleResponse($data, $status = Response::HTTP_OK, array $serializationContext = [])
    {
        $data = [
            'navigation' =>
                [
                    0 =>
                        [
                            'id' => 'AZ',
                            'name' => 'sortation',
                            'url' => 'patient-list',
                            'title' => 'Patienten-Liste',
                            'collection' => 'patient',
                            'group' => false,
                            'filter' =>
                                [
                                    'status' => 1,
                                ],
                            'filterBox' =>
                                [
                                    0 =>
                                        [
                                            'type' => 'text',
                                            'value' => 'label',
                                        ],
                                ],
                        ],
                    1 =>
                        [
                            'id' => 'group',
                            'name' => 'group',
                            'url' => 'patient-list',
                            'title' => 'Patienten-Liste',
                            'collection' => 'patient',
                            'group' => true,
                        ],
                    2 =>
                        [
                            'id' => 'archive',
                            'name' => 'archive',
                            'url' => 'patient-list-archived',
                            'title' => 'Liste der archivierten Patienten',
                            'collection' => 'patient',
                            'group' => false,
                            'filter' =>
                                [
                                    'status' => 0,
                                ],
                        ],
                ],
            'collections' =>
                [
                    'patient' => $data,
                ],
        ];

        return parent::handleResponse($data, $status, $serializationContext); // TODO: Change the autogenerated stub
    }

}